[tasks.cargo-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.leptos-format]
install_crate = "leptosfmt"
command = "leptosfmt"
args = ["app"]

[tasks.format]
dependencies = [
    "cargo-format",
    "leptos-format"
]
workspace = false

[tasks.fmt]
alias = "format"

[tasks.build]
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "serve", "-r"]
workspace = false

[tasks.serve]
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "watch", "--features", "development", "--hot-reload"]
workspace = false

[tasks.deploy]
dependencies = [ "build" ]
command = "npx"
args = ["firebase-tools", "deploy", "--only", "hosting"]
workspace = false
